# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Sync with IOC stalkerware indicators

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # weekly on Sunday at 00:00
  schedule:
    - cron: '0 0 * * 0'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    # checkout a submodule
    - name: Checkout AssoEchap/stalkerware-indicators
      uses: actions/checkout@v3
      with:
        repository: AssoEchap/stalkerware-indicators
        path: './data/stalkerware-indicators'
    - name: Update
      run: |
        python scripts/get-stalkerware-indicators.py
    - name: Create Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@v5
      with:
        add-paths: |
          static_data/app-flags.csv

        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: Update stalkerware indicators
        committer: GitHub <noreply@github.com>
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        signoff: false
        branch: ioc
        delete-branch: false
        title: '[Example] Update stalkware indicators'
        body: |
          Update stalkware indicators
          - Updated with *today's* date
          - Auto-generated by [create-pull-request][1]

          [1]: https://github.com/peter-evans/create-pull-request
        labels: |
          report
          automated pr
        assignees: rchatterjee
        reviewers: rchatterjee, naman
        draft: false
    - name: Check outputs
      if: ${{ steps.cpr.outputs.pull-request-number }}
      run: |
        echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
        echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
